// Generated by CoffeeScript 1.6.3
(function() {
  var app, cron, express, http, path, routes;

  express = require("express");

  http = require("http");

  path = require("path");

  routes = require("routes/routes");

  app = express();

  app.set("port", process.env.PORT || 3000);

  app.use(express.favicon());

  app.use(express.logger("dev"));

  app.use(express.json());

  app.use(express.urlencoded());

  app.use(express.methodOverride());

  app.use(app.router);

  app.use(express["static"](path.join(__dirname, "../gunslinger-client/")));

  if ("development" === app.get("env")) {
    app.use(express.errorHandler());
  }

  http.createServer(app).listen(app.get("port"), function() {
    return console.log("Express server listening on port " + app.get("port"));
  });

  app.get('/api/v1/upload', routes.upload(req, res));

  cron = require('./scripts/cron/instagram-email');

}).call(this);
